import React, { useEffect, useState } from "react";

import aboutImgMob from "../../Images/Png/aboutMob.png";
import aboutImgTab from "../../Images/Png/aboutTab.png";
import aboutImgDesk from "../../Images/Png/aboutDesk.png";
import {
  AboutCont,
  AboutImg,
  AboutSection,
  AboutTextOne,
  AboutTextTwo,
  AboutTitle,
  CrossIconStyled,
} from "./About.styled";
import { Container } from "../App/App.styled";

const About = () => {
  const [screenSize, setScreenSize] = useState("");

  useEffect(() => {
    const handleResize = () => {
      if (window.matchMedia("(max-width: 767px)").matches) {
        setScreenSize("small");
      } else if (
        window.matchMedia("(min-width: 768px) and (max-width: 1279px)").matches
      ) {
        setScreenSize("medium");
      } else if (window.matchMedia("(min-width: 1280px)").matches) {
        setScreenSize("large");
      }
    };

    handleResize();
    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  let imgSrc;

  switch (screenSize) {
    case "small":
      imgSrc = aboutImgMob;
      break;
    case "medium":
      imgSrc = aboutImgTab;
      break;
    case "large":
      imgSrc = aboutImgDesk;
      break;
    default:
      break;
  }

  return (
    <Container>
      <AboutSection id="about">
        <AboutTitle>
          a Story that started with <span>one simple ape</span>
        </AboutTitle>
        <AboutTextOne>
          WHO GOT {screenSize === "small" && <br />} FED UP WITH BORING AND
          HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND DYNAMIC
          JOURNEY ON THE{" "}
          {(screenSize === "medium" || screenSize === "large") && <br />} YACHT
        </AboutTextOne>
        <AboutCont>
          <CrossIconStyled />
          <AboutTextTwo>
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </AboutTextTwo>
        </AboutCont>
        <AboutImg src={imgSrc} alt="NFT monkey in glasses and cap" />
      </AboutSection>
    </Container>
  );
};

export default About;
